SET IDENTITY_INSERT [dbo].[IncidenciasPartido] ON
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (1, 1, N'GolesAFavor', 2, 1)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (2, 2, N'GolesAFavor', 2, 1)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (3, 2, N'GolesEnContra', 2, 1)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (4, 1, N'GolesEnContra', 2, 1)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (5, 2, N'Empate', 1, 1)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (6, 1, N'Empate', 1, 1)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (7, 3, N'GolesAFavor', 2, 2)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (8, 4, N'GolesAFavor', 1, 2)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (9, 4, N'GolesEnContra', 2, 2)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (10, 3, N'GolesEnContra', 1, 2)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (11, 3, N'Victoria', 3, 2)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (12, 5, N'GolesAFavor', 4, 3)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (13, 6, N'GolesAFavor', 1, 3)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (14, 6, N'GolesEnContra', 4, 3)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (15, 5, N'GolesEnContra', 1, 3)
INSERT INTO [dbo].[IncidenciasPartido] ([Id], [SeleccionId], [TipoIncidencia], [Valor], [PartidoId]) VALUES (16, 5, N'Victoria', 3, 3)
SET IDENTITY_INSERT [dbo].[IncidenciasPartido] OFF
